name: travelmex
description: "Aplicación de turismo TravelMex con Flutter y Supabase."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Conexión con Base de Datos
  supabase_flutter: ^2.0.2

  # Mapa real
  google_maps_flutter: ^2.4.0

  # Estética y Diseño
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.6.0

  # Utilidades
  intl: ^0.19.0
  cupertino_icons: ^1.0.6

  # Estado y Arquitectura
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Configuración de imágenes locales
  assets:
    - assets/images/
    - assets/icons/

